services:
  haproxy:
    image: haproxy:2.3-alpine
    command: haproxy -f /etc/haproxy/haproxy.cfg
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/dev/haproxy/:/etc/haproxy/
    networks:
      - default

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./config:/opt/app/config:cached
      - ./lib:/opt/app/lib:cached
      - ./priv:/opt/app/priv:cached
      - ./test:/opt/app/test:cached
    networks:
      - default